---
  # Общие параметры, то, что нужно менять 
  nginx_main_server_port: 8019
  #tomcat_server_port: 8020
  wildfly_http_server_port: 8020
  wildfly_management_http_server_port: 8021
  wildfly_https_server_port: 8022
  wildfly_management_https_server_port: 8023

  # Менять не рекомендуется.  
  java_home: "/usr/local/openjdk17" # Путь жабы на гелиосе
  base_path: "/home/{{ansible_user}}" # данная переменная переопределяется именно для гелиоса в general_inventory/host_vars/helios_cs_ifmo.yml
  make_archive: "make-4.4.1"
  make_tar_link: "http://ftp.gnu.org/gnu/make/{{make_archive}}.tar.gz"
  nginx_archive: "nginx-1.28.0"
  nginx_tar_link: "https://nginx.org/download/{{nginx_archive}}.tar.gz"
  
  nginx_server_name: helios.cs.ifmo.ru
  pcre_archive: "pcre-8.45"
  pcre_tar_link: "https://sourceforge.net/projects/pcre/files/pcre/8.45/{{pcre_archive}}.tar.gz"
  zlib_archive: "zlib-1.3.1"
  zlib_tar_link: "http://zlib.net/{{zlib_archive}}.tar.gz"
  nginx_configure_vars: "--with-http_v2_module \
            --with-http_stub_status_module \
            --without-http_autoindex_module \
            --with-pcre={{base_path}}/autodeploy/install_tmp/{{pcre_archive}} \
            --with-zlib={{base_path}}/autodeploy/install_tmp/{{zlib_archive}}"
  nginx_build_env: "MAKE=\"gmake\""
  zlib_build_env: "MAKE=\"gmake\""
  commons_daemon_build_env: "JAVA_HOME={{java_home}} MAKE=\"gmake\" PATH={{base_path}}/autodeploy/libs/autoconf/bin:$PATH"
  wait_from_startup: 8
  forwarding_container_name: "forwarding"
  forwarding_image_name: "forwarding"
  host_binded_port_for_nginx: "{{nginx_main_server_port}}"
  host_binded_port_for_wildfly: "{{wildfly_http_server_port}}"
  host_binded_port_for_wildfly_management: "{{wildfly_management_http_server_port}}"
  db_host: "pg"
  db_user: "{{ansible_user}}"
  db_database: "studs"
  db_pass: ""
  build_war_path: "{{hostvars[groups['deploy-helper'][0]]['base_path']}}/autodeploy/install_tmp/build_artifacts/backend_{{project_name}}.war"
  wildfly_archive: "wildfly-37.0.1.Final"
  wildfly_tar_link: "https://github.com/wildfly/wildfly/releases/download/37.0.1.Final/{{wildfly_archive}}.tar.gz"
  wildfly_screen_session_name: "wildfly"
  wildfly_start_params: "
    -Djboss.http.port={{wildfly_http_server_port}} \
    -Djboss.management.http.port={{wildfly_management_http_server_port}} \
    -Djboss.https.port={{wildfly_https_server_port}} \
    -Djboss.management.https.port={{wildfly_management_https_server_port}} \
    "
  wildfly_start_env: "JAVA_OPTS=\"-Xmx2g -Xms256m -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1g\""
  wildfly_cli_env: "JAVA_OPTS=\"-Xmx64m -Xms32m\""
  wildfly_user: "wildfly"
  wildfly_password: "wildfly"
  wildfly_deployment_name: "backend_{{project_name}}"
  

  