\set ON_ERROR_STOP on
SET database.deployname = 'lab1';
\i remove.sql

BEGIN;
CALL start_deployment();
COMMIT;

BEGIN;
CREATE TABLE LAB1_DIFFICULTY (
    ID SERIAL PRIMARY KEY,
    VAL VARCHAR(255) NOT NULL UNIQUE
);
INSERT INTO LAB1_DIFFICULTY (ID, VAL) VALUES (1,'VERY_EASY'), (2,'EASY'), (3, 'VERY_HARD');

CREATE TABLE LAB1_COLOR (
    ID SERIAL PRIMARY KEY,
    VAL VARCHAR(255) NOT NULL UNIQUE
);
INSERT INTO LAB1_COLOR (ID, VAL) VALUES (1,'RED'), (2,'BLACK'), (3, 'BLUE'), (4, 'BROWN');

CREATE TABLE LAB1_COUNTRY (
    ID SERIAL PRIMARY KEY,
    VAL VARCHAR(255) NOT NULL UNIQUE
);
INSERT INTO LAB1_COUNTRY (ID, VAL) VALUES (1,'CHINA'), (2,'INDIA'), (3, 'ITALY'), (4, 'SOUTH_KOREA');

CREATE TABLE LAB1_LOCATION(
    ID SERIAL PRIMARY KEY,
    X FLOAT NOT NULL,
    Y FLOAT NOT NULL,
    Z FLOAT,
    NAME VARCHAR(702) NOT NULL CHECK (TRIM(NAME) != '')
);

CREATE TABLE LAB1_COORDINATE(
    ID SERIAL PRIMARY KEY,
    X FLOAT CHECK (X <= 292) NOT NULL,
    Y FLOAT CHECK (Y > -244) NOT NULL
);

CREATE TABLE LAB1_DISCIPLINE(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(400) NOT NULL CHECK (TRIM(NAME) != ''),
    LABS_COUNT INTEGER NOT NULL CHECK (LABS_COUNT > 0)
);

CREATE TABLE LAB1_PERSON(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(400) NOT NULL CHECK (TRIM(NAME) != ''), 
    EYE_COLOR INTEGER NOT NULL,
    HAIR_COLOR INTEGER,
    LOCATION_ID INTEGER,
    PASSPORT_ID VARCHAR(50) CHECK ((PASSPORT_ID IS NULL) OR ((TRIM(PASSPORT_ID) != '') AND LENGTH(PASSPORT_ID) >= 5)),
    NATIONALITY_ID INTEGER,
    FOREIGN KEY (LOCATION_ID) REFERENCES LAB1_LOCATION(ID),
    FOREIGN KEY (EYE_COLOR) REFERENCES LAB1_COLOR(ID),
    FOREIGN KEY (HAIR_COLOR) REFERENCES LAB1_COLOR(ID) ,
    FOREIGN KEY (NATIONALITY_ID) REFERENCES LAB1_COUNTRY(ID)
);

CREATE TABLE LAB1_LABWORK(
    ID SERIAL PRIMARY KEY CHECK (ID > 0),
    NAME VARCHAR(400) NOT NULL CHECK (TRIM(NAME) != ''),
    COORDINATES_ID INTEGER NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL default NOW(),
    DESCRIPTION TEXT NOT NULL,
    DIFFICULTY_ID INTEGER,
    DISCIPLINE_ID INTEGER,
    MINIMAL_POINT FLOAT NOT NULL CHECK (MINIMAL_POINT > 0),
    MAXIMUM_POINT FLOAT CHECK (MAXIMUM_POINT > 0),
    AUTHOR_ID INTEGER,
    FOREIGN KEY (DISCIPLINE_ID) REFERENCES LAB1_DISCIPLINE(ID),
    FOREIGN KEY (COORDINATES_ID) REFERENCES LAB1_COORDINATE(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES LAB1_PERSON(ID),
    FOREIGN KEY (DIFFICULTY_ID) REFERENCES LAB1_DIFFICULTY(ID)
);

CREATE TABLE LAB1_YAML_IMPORT_HISTORY(
    id serial primary key,
    time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    status varchar(255) NOT NULL,
    imported_objects INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    filename varchar(512),
    original_filename varchar(512)
);
CALL end_deployment();
COMMIT;
