---  
  - name: Build backend
    hosts: deploy-helper
    tasks: 
      - name: Ensure that directory "build_src" exists
        file:
          path: "{{base_path}}/autodeploy/install_tmp/build_src/"
          state: directory 
      
      - name: Ensure that build directory for lab exists
        file:
          path: "{{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/"
          state: directory 
      
      - name: Remove all old build srcs 
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/ && rm -rf *"

      - name: Copy backend src
        synchronize:
          src: "/host_dirs/{{project_name}}/backend/"
          dest: "{{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/"
      
      - name: Determine is it maven or gradle
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/ && ls | grep pom.xml"
        register: pom_xml_search_result
        failed_when: pom_xml_search_result.rc not in [0,1]

      - name: Maven clean
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/ && mvn clean package"
        when: pom_xml_search_result.rc == 0
      
      - name: Maven build
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/ && mvn package"
        when: pom_xml_search_result.rc == 0
      
      - name: Gradle build
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/ && gradle build"
        when: pom_xml_search_result.rc == 1
      
      - name: Set artifact path
        set_fact:
          artifact_path: "{{'target' if pom_xml_search_result.rc == 0 else 'build/libs'}}"

      - name: Determine is it standalone or web archive
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/{{artifact_path}} && ls | grep .jar"
        register: jar_search_result
        failed_when: jar_search_result.rc not in [0,1]
      
      - name: Ensure that build_artifacts dir existst
        file:  
          path: "{{base_path}}/autodeploy/install_tmp/build_artifacts"
          state: directory

      - name: Copy jar artifacts
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/{{artifact_path}} && \
          cp *.jar {{base_path}}/autodeploy/install_tmp/build_artifacts/backend_{{project_name}}.jar"
        when: jar_search_result.rc == 0
      
      - name: Remove misleading war files
        file:  
          path: "{{base_path}}/autodeploy/install_tmp/build_artifacts/backend_{{project_name}}.war"
          state: absent 
        when: jar_search_result.rc == 0
      
      - name: Copy war artifacts
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_src/{{project_name}}/{{artifact_path}} && \
          cp *.war {{base_path}}/autodeploy/install_tmp/build_artifacts/backend_{{project_name}}.war"
        when: jar_search_result.rc == 1
      
      - name: Remove misleading jar files
        file:  
          path: "{{base_path}}/autodeploy/install_tmp/build_artifacts/backend_{{project_name}}.jar"
          state: absent 
        when: jar_search_result.rc == 1

      
      