---  
  - name: Check the artifacts
    hosts: deploy-helper
    tasks: 
      - name: Determine is it standalone
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_artifacts/ \ 
          && ls | grep backend_{{project_name}}.jar"
        register: jar_search_result
        failed_when: jar_search_result.rc not in [0,1]

      - name: Determine is it web archive
        shell: "cd {{base_path}}/autodeploy/install_tmp/build_artifacts/ \ 
          && ls | grep backend_{{project_name}}.war"
        register: war_search_result
        failed_when: war_search_result.rc not in [0,1]
      
      - name: Fail if not found
        fail:
          msg: Unable to find backend artifact, run build first.
        when: war_search_result.rc == 1 and war_search_result.rc == 1
      
      - name: Set fact
        set_fact:
          war_deploy: war_search_result

  - name: Deploy webarchive backend
    hosts: deploy-servers
    vars:
      wildfly_cli: "{{wildfly_cli_env}} {{base_path}}/autodeploy/wildfly/bin/jboss-cli.sh --connect --controller=localhost:{{wildfly_management_http_server_port}}"
    tasks: 
      - name: Skip tasks if backend isn't a webarchive
        meta: end_play
        when: hostvars[groups['deploy-helper'][0]]['war_deploy'] == 1

      - name: Get current deployment status
        shell: "{{wildfly_cli}} --command='deployment-info --name=backend_{{project_name}}.war'"
        register: is_already_deployed
        ignore_errors: yes
      
      - name: Undeploy application if running
        shell: "{{wildfly_cli}} --command='undeploy backend_{{project_name}}.war'"
        when: is_already_deployed.rc == 0
      
      - name: Copy war to host
        copy:
          src:  "{{hostvars[groups['deploy-helper'][0]]['base_path']}}/autodeploy/install_tmp/build_artifacts/backend_{{project_name}}.war"
          dest: "{{base_path}}/autodeploy/install_tmp/backend_{{project_name}}.war"
      
      - name: Deploy new version
        shell: "{{wildfly_cli}} --command='deploy {{base_path}}/autodeploy/install_tmp/backend_{{project_name}}.war'"
      
      - name: Copy nginx backend conf
        template:
          src: "/host_dirs/lab_installer/templates/nginx/conf/backend_wildfly.j2"
          dest: "{{base_path}}/autodeploy/nginx/conf/conf.d/backend_{{project_name}}.conf"
      
      - name: Copy nginx upstream conf
        template:
          src: "/host_dirs/lab_installer/templates/nginx/conf/upstream_wildfly.j2"
          dest: "{{base_path}}/autodeploy/nginx/conf/conf.d/upstream_{{project_name}}.conf"
      
      - name: Reload nginx 
        shell: "cd {{base_path}}/autodeploy/nginx/sbin/ && ./nginx -s reload"
       
      
      