---  
  - name: Deploy frontend
    hosts: deploy-servers
    tasks: 
      - name: Ensure that project dir exists in nginx
        file:
          path: "{{base_path}}/autodeploy/nginx/html/{{project_name}}"
          state: directory 
      
      - name: Remove old content
        shell: "cd {{base_path}}/autodeploy/nginx/html/{{project_name}} && rm -rf *"
      
      - name: Copy files from build
        copy:
          src:  "{{hostvars[groups['deploy-helper'][0]]['base_path']}}/autodeploy/install_tmp/build_artifacts/{{project_name}}/"
          dest: "{{base_path}}/autodeploy/nginx/html/{{project_name}}/"

      