---  
  - name: Restart containers
    hosts: deploy-servers
    tasks: 
      - name: Try to stop nginx
        shell: "cd {{base_path}}/autodeploy/nginx/sbin/ && ./nginx -s quit"
        ignore_errors: true

      - name: Start nginx
        shell: "cd {{base_path}}/autodeploy/nginx/sbin/ && ./nginx"
      
      - name: Wait some time
        ansible.builtin.pause:
          seconds: "{{wait_from_startup}}"
      
      - name: Get PID file content
        slurp:
          src: "{{base_path}}/autodeploy/nginx/logs/nginx.pid"
        register: nginx_pid
      
      - name: Check if nginx alive
        shell: "ps aux | grep {{ nginx_pid.content | b64decode | trim }} | grep -v grep"

      - name: Try to stop wildfly screen session
        shell: "screen -X -S {{wildfly_screen_session_name}} quit"
        ignore_errors: true
      
      - name: Try to stop wildfly 
        shell: "kill $(jps -lv | grep {{base_path}}/autodeploy/wildfly/jboss-modules.jar | awk '{print $1}')"
        ignore_errors: true

      - name: Start wildfly
        shell: "cd {{base_path}}/autodeploy/wildfly/bin && {{wildfly_start_env}} screen -dmS {{wildfly_screen_session_name}} ./standalone.sh {{wildfly_start_params}}"
      
      - name: Wait some time
        ansible.builtin.pause:
          seconds: "{{wait_from_startup}}"
      
      - name: Check if wildfly alive
        shell: "ps -eww | grep  {{base_path}}/autodeploy/wildfly/jboss-modules.jar | grep -v grep"
      
