---  
  - name: Deploy nginx
    hosts: deploy-servers
    tasks: 
      - name: Get tomcat tar
        get_url:
          url:  "{{tomcat_tar_link}}"
          dest: "{{base_path}}/autodeploy/install_tmp/"

      - name: Untar tomcat 
        command: "tar -xvzf {{base_path}}/autodeploy/install_tmp/{{tomcat_archive}}.tar.gz -C {{base_path}}/autodeploy/install_tmp/"
      
      - name: Copy to tomcat dir
        copy:
          src:  "{{base_path}}/autodeploy/install_tmp/{{tomcat_archive}}/"
          dest: "{{base_path}}/autodeploy/tomcat/"
          remote_src: yes