---  
  - name: Deploy wildfly Jakarta EE
    hosts: deploy-servers
    tasks: 
      - name: Get wildfly tar
        get_url:
          url:  "{{wildfly_tar_link}}"
          dest: "{{base_path}}/autodeploy/install_tmp/"

      - name: Untar wildfly 
        command: "tar -xvzf {{base_path}}/autodeploy/install_tmp/{{wildfly_archive}}.tar.gz -C {{base_path}}/autodeploy/install_tmp/"
      
      - name: Try to stop wildfly screen session
        shell: "screen -X -S {{wildfly_screen_session_name}} quit"
        ignore_errors: true
      
      - name: Try to stop wildfly 
        shell: "kill $(jps -lv | grep {{base_path}}/autodeploy/wildfly/jboss-modules.jar | awk '{print $1}')"
        ignore_errors: true

      - name: Copy to wildfly dir
        copy:
          src:  "{{base_path}}/autodeploy/install_tmp/{{wildfly_archive}}/"
          dest: "{{base_path}}/autodeploy/wildfly/"
          remote_src: yes
      
      - name: Create WildFly management user
        shell: "cd {{base_path}}/autodeploy/wildfly/bin/ && JAVA_OPTS=\"-Xmx128m -Xms32m\" ./add-user.sh {{wildfly_user}} {{wildfly_password}}"



      
      
