BEGIN;
CREATE TABLE IF NOT EXISTS DEPLOYMENTS (
    ID SERIAL PRIMARY KEY,
    DEPLOY_NAME VARCHAR(255) NOT NULL UNIQUE,
    FIRST_DEPLOY_DATE TIMESTAMP NOT NULL default NOW(),
    DEPLOY_DATE TIMESTAMP NOT NULL default NOW(),
    SUCCESSFUL BOOLEAN 
);

CREATE OR REPLACE FUNCTION check_last_deployment()
RETURNS BOOLEAN AS $$
DECLARE
    deploy_id NUMERIC;
BEGIN
    SELECT ID INTO deploy_id FROM DEPLOYMENTS WHERE DEPLOY_NAME = CURRENT_SETTING('database.deployname');
    RETURN NOT (deploy_id IS NULL);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE start_deployment() AS $$
BEGIN
    INSERT INTO DEPLOYMENTS (DEPLOY_NAME, SUCCESSFUL) VALUES (CURRENT_SETTING('database.deployname'), false);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE end_deployment() AS $$
DECLARE
    deploy_id NUMERIC;
BEGIN
    SELECT ID INTO deploy_id FROM DEPLOYMENTS WHERE DEPLOY_NAME = CURRENT_SETTING('database.deployname');
    UPDATE DEPLOYMENTS 
    SET SUCCESSFUL = true
    WHERE ID = deploy_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE delete_deployment() AS $$
DECLARE
    deploy_id NUMERIC;
BEGIN
    SELECT ID INTO deploy_id FROM DEPLOYMENTS WHERE DEPLOY_NAME = CURRENT_SETTING('database.deployname');
    DELETE FROM DEPLOYMENTS WHERE ID = deploy_id;
END;
$$ LANGUAGE plpgsql;

COMMIT;