BEGIN;

CREATE TYPE LAB1_DIFFICULTY as enum (
    'VERY_EASY',
    'EASY',
    'VERY_HARD'
);

CREATE TYPE LAB1_COLOR as enum (
    'RED',
    'BLACK',
    'BLUE',
    'BROWN'
);

CREATE TYPE LAB1_COUNTRY as enum (
    'CHINA',
    'INDIA',
    'ITALY',
    'SOUTH_KOREA'
);

CREATE TABLE LAB1_LOCATION(
    ID SERIAL PRIMARY KEY,
    X FLOAT NOT NULL,
    Y FLOAT NOT NULL,
    Z FLOAT NOT NULL,
    NAME VARCHAR(702) NOT NULL CHECK (TRIM(NAME) != '')
);

CREATE TABLE LAB1_COORDINATES(
    ID SERIAL PRIMARY KEY,
    X FLOAT CHECK (X <= 292),
    Y FLOAT CHECK (Y > -244)
);

CREATE TABLE LAB1_DISCIPLINE(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(400) NOT NULL CHECK (TRIM(NAME) != ''),
    LABS_COUNT INTEGER NOT NULL CHECK (LABS_COUNT > 0)
);

CREATE TABLE LAB1_PERSON(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(400) NOT NULL CHECK (TRIM(NAME) != ''),
    EYE_COLOR LAB1_COLOR NOT NULL,
    HAIR_COLOR LAB1_COLOR,
    LOCATION_ID INTEGER,
    PASSPORT_ID VARCHAR(50) CHECK ((PASSPORT_ID IS NULL) OR ((TRIM(PASSPORT_ID) != '') AND LENGTH(PASSPORT_ID) >= 5)),
    NATIONALITY_ID LAB1_COUNTRY,
    FOREIGN KEY (LOCATION_ID) REFERENCES LAB1_LOCATION(ID) ON DELETE SET NULL
);

CREATE TABLE LAB1_LABWORK(
    ID SERIAL PRIMARY KEY CHECK (ID > 0),
    NAME VARCHAR(400) NOT NULL CHECK (TRIM(NAME) != ''),
    COORDINATES_ID INTEGER NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL default NOW(),
    DESCRIPTION TEXT NOT NULL,
    DIFFICULTY LAB1_DIFFICULTY,
    DISCIPLINE_ID INTEGER,
    MINIMAL_POINT FLOAT NOT NULL CHECK (MINIMAL_POINT > 0),
    MAXIMUM_POINT FLOAT CHECK (MAXIMUM_POINT > 0),
    AUTHOR_ID INTEGER,
    FOREIGN KEY (COORDINATES_ID) REFERENCES LAB1_COORDINATES(ID),
    FOREIGN KEY (DISCIPLINE_ID) REFERENCES LAB1_DISCIPLINE(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES LAB1_PERSON(ID)
);

COMMIT;