BEGIN;

DROP TABLE IF EXISTS LAB1_LABWORK;
DROP TABLE IF EXISTS LAB1_PERSON;
DROP TABLE IF EXISTS LAB1_DISCIPLINE;
DROP TABLE IF EXISTS LAB1_COORDINATES;
DROP TABLE IF EXISTS LAB1_LOCATION;
DROP TYPE IF EXISTS LAB1_DIFFICULTY;
DROP TYPE IF EXISTS LAB1_COLOR;
DROP TYPE IF EXISTS LAB1_COUNTRY;

COMMIT;
