\set ON_ERROR_STOP on
SET database.deployname = 'lab1';
\i common.sql

BEGIN;

DROP TABLE IF EXISTS LAB1_LABWORK;
DROP TABLE IF EXISTS LAB1_PERSON;
DROP TABLE IF EXISTS LAB1_DISCIPLINE;
DROP TABLE IF EXISTS LAB1_COORDINATES;
DROP TABLE IF EXISTS LAB1_LOCATION;
DROP TABLE IF EXISTS LAB1_DIFFICULTY;
DROP TABLE IF EXISTS LAB1_COLOR;
DROP TABLE IF EXISTS LAB1_COUNTRY;

COMMIT;
