\set ON_ERROR_STOP on
SET database.deployname = 'lab1';
\i common.sql

BEGIN;
DO $$
DECLARE 
BEGIN
    IF check_last_deployment() THEN
        DROP TABLE IF EXISTS LAB1_LABWORK;
        DROP TABLE IF EXISTS LAB1_PERSON;
        DROP TABLE IF EXISTS LAB1_DISCIPLINE;
        DROP TABLE IF EXISTS LAB1_COORDINATES;
        DROP TABLE IF EXISTS LAB1_LOCATION;
        DROP TABLE IF EXISTS LAB1_DIFFICULTY;
        DROP TABLE IF EXISTS LAB1_COLOR;
        DROP TABLE IF EXISTS LAB1_COUNTRY;
        CALL delete_deployment();
    END IF;
END;
$$;
COMMIT;

