com.atomikos.icatch.service=com.atomikos.icatch.standalone.UserTransactionServiceFactory
com.atomikos.icatch.max_timeout=300000
com.atomikos.icatch.default_jta_timeout=10000
com.atomikos.icatch.max_actives=50
com.atomikos.icatch.log_base_dir=./transactions
com.atomikos.icatch.output_dir=./transactions
com.atomikos.icatch.force_shutdown_on_vm_exit=true
com.atomikos.icatch.automatic_resource_registration=true
com.atomikos.icatch.threaded_2pc=true