BEGIN;

CREATE TABLE IF NOT EXISTS ALL_DEPLOYMENTS (
    ID SERIAL PRIMARY KEY,
    DEPLOY_NAME VARCHAR(255) NOT NULL UNIQUE,
    FIRST_DEPLOY_DATE TIMESTAMP NOT NULL default NOW()
);

CREATE TABLE IF NOT EXISTS CURRENT_DEPLOYMENTS (
    ID SERIAL PRIMARY KEY,
    DEPLOY_NAME VARCHAR(255) NOT NULL UNIQUE,
    DEPLOY_DATE TIMESTAMP NOT NULL default NOW(),
    SUCCESSFUL BOOLEAN,
    FOREIGN KEY (DEPLOY_NAME) REFERENCES ALL_DEPLOYMENTS(DEPLOY_NAME)
);



CREATE OR REPLACE VIEW DEPLOYMENTS AS
SELECT 
    CURRENT_DEPLOYMENTS.ID AS ID,
    CURRENT_DEPLOYMENTS.DEPLOY_NAME AS DEPLOY_NAME,
    FIRST_DEPLOY_DATE,
    DEPLOY_DATE,
    SUCCESSFUL
FROM ALL_DEPLOYMENTS
INNER JOIN CURRENT_DEPLOYMENTS ON ALL_DEPLOYMENTS.DEPLOY_NAME = CURRENT_DEPLOYMENTS.DEPLOY_NAME;

CREATE OR REPLACE FUNCTION check_last_deployment_exists()
RETURNS BOOLEAN AS $$
DECLARE
    deploy_id NUMERIC;
BEGIN
    SELECT ID INTO deploy_id FROM CURRENT_DEPLOYMENTS WHERE DEPLOY_NAME = CURRENT_SETTING('database.deployname');
    RETURN NOT (deploy_id IS NULL);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE start_deployment() AS $$
DECLARE
    deploy_all_id NUMERIC;
BEGIN
    SELECT ID INTO deploy_all_id FROM ALL_DEPLOYMENTS WHERE DEPLOY_NAME = CURRENT_SETTING('database.deployname');
    IF deploy_all_id IS NULL THEN
        INSERT INTO ALL_DEPLOYMENTS (DEPLOY_NAME) VALUES (CURRENT_SETTING('database.deployname'));
    END IF;
    INSERT INTO CURRENT_DEPLOYMENTS (DEPLOY_NAME, SUCCESSFUL) VALUES (CURRENT_SETTING('database.deployname'), false);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE end_deployment() AS $$
DECLARE
    deploy_id NUMERIC;
BEGIN
    SELECT ID INTO deploy_id FROM CURRENT_DEPLOYMENTS WHERE DEPLOY_NAME = CURRENT_SETTING('database.deployname');
    UPDATE CURRENT_DEPLOYMENTS 
    SET SUCCESSFUL = true
    WHERE ID = deploy_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE delete_deployment() AS $$
DECLARE
    deploy_id NUMERIC;
BEGIN
    SELECT ID INTO deploy_id FROM CURRENT_DEPLOYMENTS WHERE DEPLOY_NAME = CURRENT_SETTING('database.deployname');
    DELETE FROM CURRENT_DEPLOYMENTS WHERE ID = deploy_id;
END;
$$ LANGUAGE plpgsql;

COMMIT;